### PR TITLE
chore: pass usage app name to coder ssh

### PR DESCRIPTION
**Pull request by f0ssel**
Relies on https://github.com/coder/coder/pull/13637. 

This signals to the CLI to track workspace usage with the `jetbrains` usage app name.

### CODE REVIEW

**Comment by f0ssel** [comment]
Both locally and in CI I'm seeing this fail to build with the following error:

`> Could not find com.jetbrains.gateway:JetBrainsGateway:233.14808-EAP-CANDIDATE-SNAPSHOT.`
https://github.com/coder/jetbrains-coder/actions/runs/9628941608/job/26557738545?pr=442#step:5:329

**Review by code-asher — COMMENTED** [review]
It looks good to me!  Though I mentioned this on the other PR but I think we will have to use the flag after all for Windows.  We could check against the CLI version before adding the flag.  There is some precedence for it here:

https://github.com/coder/jetbrains-coder/blob/dceb57863b3e66e89be9124871404b1a3415159a/src/main/kotlin/com/coder/gateway/cli/CoderCLIManager.kt#L448

**Comment by f0ssel** [comment]
@code-asher I've updated it to check the version and use the flag, thanks for the catch on the windows compatibility.

**Review by code-asher — APPROVED** [review]
Awesome!!

**Pull request merged**
